### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by AC-Meira** [dirty-cat/dirty_cat#131] opened 2020-07-02 02:57 UTC
Hello!

I was trying to reproduce "Investigating dirty categories" (https://dirty-cat.github.io/stable/auto_examples/01_investigating_dirty_categories.html#sphx-glr-auto-examples-01-investigating-dirty-categories-py) and got this error: AttributeError: 'tuple' object has no attribute 'shape'.

Log says it is in line 241, in fit n_samples, n_features = X.shape

Am I doing something wrong or is it a issue?

I'm on python 3.7.

Thanks

**Comment by amy12xx** [comment] 2020-07-02 04:08
are you using it on your own dataset? If so, may be it is not in the expected datatype (numpy or pandas array)?

**Comment by AC-Meira** [comment] 2020-07-03 14:39
Yes, I'm using another dataset (https://www.kaggle.com/osmi/mental-health-in-tech-survey).
The variable I'm passing is a numpy.ndarray. 
Follow my code:

```
dataset_C = pd.read_csv('mental-health-in-tech-survey.csv')
dataset_C.info()
values = dataset_C[['Gender', 'Country', 'state']]
sorted_values = values['Gender'].sort_values().unique()
sorted_values
type(sorted_values)
similarity_encoder = SimilarityEncoder(similarity='ngram')
transformed_values = similarity_encoder.fit_transform(sorted_values.reshape(-1, 1))
```

And log:
[log_dirty_cat_test.txt](https://github.com/dirty-cat/dirty_cat/files/4870197/log_dirty_cat_test.txt)

**Comment by anhtholee** [comment] 2020-07-30 16:45
I just had the same issue. Have you been able to fix it? I think the problem is from this line:
```
X = self._check_X(X)
```
That `_check_X` method returns a tuple according to  [this line](https://github.com/scikit-learn/scikit-learn/blob/fd237278e895b42abe8d8d09105cbb82dc2cbba7/sklearn/preprocessing/_encoders.py#L64) from scikit-learn's repo, hence the error.

**Comment by AC-Meira** [comment] 2020-08-01 00:11
Unfortunately I didn't have time to fix it and went for another solution to my problem.
But I'm still very interested in this encoder. If I have any news I'll post it here. And please, if you have something too, let me know.

**Comment by amy12xx** [comment] 2020-08-01 06:10
This looks to be fixed in the source (not yet released) version.

**Comment by GaelVaroquaux** [comment] 2020-08-02 15:26
I should do a release. Let's see if I can do that today...

**Comment by GaelVaroquaux** [comment] 2020-08-02 16:08
I've made a new release: https://pypi.org/project/dirty-cat/

```
python -m pip install --upgrade dirty-cat
```
should fix the problem.

Tell us if it works!

**Comment by AC-Meira** [comment] 2020-08-11 00:34
Yeah! It's working!
Thanks!
@anhtholee Is it working for you too?
I think we can close this issue, right?

**Comment by anhtholee** [comment] 2020-08-11 02:59
@AC-Meira Yes it worked for me too.

**Closed** 2020-08-12 18:09 UTC

**Comment by GaelVaroquaux** [comment] 2020-08-12 19:12
Great! Thanks a lot!!
